---
- name: Bootstrap development environment
  hosts: localhost
  tasks:

    - name: Distribution Name
      debug: msg="{{ ansible_distribution }}"

    - name: Update all submodules
      tags:
        - submodules
      command:
        cmd: git submodule update --force --init --recursive --jobs 4
      changed_when: false

    - name: Pre-install
      tags: pre_install
      import_role:
        name: pre_install

    - name: Common tools
      tags: common
      import_role:
        name: common

    - name: Archlinux Setup
      tags: archlinux
      import_role:
        name: archlinux
      when: ansible_distribution == "Archlinux"

    - name: macOS Setup
      tags: macos
      import_role:
        name: macos
      when: ansible_distribution == "MacOSX"

    - name: Ubuntu Setup
      tags: ubuntu
      import_role:
        name: ubuntu
      when: ansible_distribution == "Ubuntu"

    - name: zsh
      tags: zsh
      import_role:
        name: zsh
      when: (ansible_distribution == "Archlinux") or
            (ansible_distribution == "Ubuntu")

    - name: Fonts
      tags: fonts
      import_role:
        name: fonts

    - name: ssh
      tags: ssh
      import_role:
        name: ssh
      when: (ansible_distribution == "Archlinux") or
            (ansible_distribution == "MacOSX") or
            (ansible_distribution == "Ubuntu")

    - name: dotfiles
      tags: dotfiles
      import_role:
        name: dotfiles
      when: (ansible_distribution == "Archlinux") or
            (ansible_distribution == "MacOSX") or
            (ansible_distribution == "Ubuntu")
