- tags: aur
  block:

  - name: Install AUR packages
    kewlfft.aur.aur:
      use: yay
      name: "{{ item.name | default(item) }}"
      state: present
    loop: "{{ arch_aur_pkgs }}"
    ignore_errors: true
