- tags: cron
  block:

  - name: Install cronie
    become: true
    pacman:
      name: cronie
      state: present

  - name: Enable cronie
    become: true
    service:
      name: cronie.service
      enabled: yes 
      state: started