- tags: desktop
  block:

    - name: install Plasma desktop and SDDM
      become: true
      pacman:
        name: 
          #- plasma-meta
          #- kde-applications-meta
          - plasma-desktop
          - sddm-kcm
        state: present
      
    - name: Install essential KDE applications
      become: true
      become_user: root
      pacman:
      # https://community.kde.org/Distributions/Packaging_Recommendations
        name:
          - ark
          - dolphin
          - gwenview
          - kcalc
          - konsole
          - kwrite
          - okular
          - spectacle
          - konsole
          - breeze-gtk
          - kde-gtk-config
          - khotkeys
          - kinfocenter
          - ksshaskpass
          - kwallet-pam
          - plasma-browser-integration
          - plasma-nm
          - plasma-pa
          - bluedevil
          - ffmpegthumbs
          - dolphin-plugins
          - kdegraphics-thumbnailers
          - kdesdk-thumbnailers
          - kdenetwork-filesharing
        state: present

    - name: Enable service sddm
      become: true
      systemd:
        name: sddm.service
        enabled: true

    # TODO: configure SDDM to breeze as default theme