---

- name: Copy pacman configuration file
  become: true
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf

- name: Refresh pacman mirrors
  pacman:
    update_cache: yes

- name: Install inetutils for hostname
  pacman:
      name: inetutils
      state: present

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined

- include_tasks: pacman.yml
- include_tasks: system.yml
- include_tasks: yay.yml
- include_tasks: desktop.yml
- include_tasks: wayland.yml
- include_tasks: bluetooth.yml
- include_tasks: cron.yml