- tags: pacman
  block:

  - name: Copy pacman configuration file
    become: true
    copy:
      src: pacman.conf
      dest: /etc/pacman.conf

  - name: Refresh pacman mirrors
    become: true
    pacman:
      update_cache: yes