- tags: pacman
  block:

    - name: pacman - Enable colored output, verbose lists and parallel downloads
      become: true
      ansible.builtin.lineinfile:
        dest: /etc/pacman.conf
        regexp: '{{ item.regex }}'
        line: '{{ item.line }}'
      loop:
        - { regex: "^#Color", line: "Color" }
        - { regex: "^#VerbosePkgLists", line: "VerbosePkgLists" }
        - { regex: "^#ParallelDownloads", line: "ParallelDownloads = 10" }


