- name: Install Pacman packages on Archlinux
  become: true
  pacman:
    state: latest
    name: "{{ item.name | default(item) }}"
  loop: "{{ arch_pkgs }}"
  when: ansible_distribution == "Archlinux"