zsh_common_pkgs:
    - zsh                             # A very advanced and programmable command interpreter (shell) for UNIX
    - zsh-autosuggestions             # Fish-like autosuggestions for zsh
    - zsh-syntax-highlighting         # Fish shell like syntax highlighting for Zsh