---
- name: Install OpenSSH on Ubuntu
  when: ansible_distribution == "Ubuntu"
  become: true
  ansible.builtin.apt:
    name: openssh-server
    state: present

- name: Enable and start OpenSSH
  when: ansible_distribution == "Ubuntu"
  become: true
  service:
    name: ssh.service
    enabled: yes
    state: started