---
- tags: macos

  block:
    - name: Install Homebrew casks (macOS)
      homebrew_cask:
        name: "{{ item.name | default(item) }}"
        state: present
        install_options: "{{ item.install_options | default('appdir=/Applications') }}"
      loop: "{{ macos_casks }}"
      when: ansible_distribution == "MacOSX"