---
- name: Install OpenSSH on Archlinux
  pacman:
    name: openssh
    state: present
  when: ansible_distribution == "Archlinux"

- name: Install OpenSSH on Ubuntu
  ansible.builtin.apt:
    name: openssh
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Enable and start OpenSSH
  service:
    name: sshd.service
    enabled: yes
    state: started
  when: ssh.enable_sshd is defined and ssh.enable_sshd == True

- name: Disable and stop OpenSSH
  service:
    name: sshd.service
    enabled: no
    state: stopped
  when: ssh.enable_sshd is defined and ssh.enable_sshd == False

- name: Make directory for user SSH key
  file:
    path: /home/{{ user.name }}/.ssh
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Install user SSH key
  copy:
    src: "{{ ssh.user_key }}"
    dest: /home/{{ user.name }}/.ssh/id_rsa
    mode: 600
    owner:  "{{ user.name }}"
    group: "{{ user.group }}"
  when: ssh.user_key is defined