---
- include_tasks: archlinux.yml
- include_tasks: ubuntu.yml
- include_tasks: macos.yml

- name: Make directory for user SSH key
  file:
    path: /home/{{ user }}/.ssh
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  ignore_errors: true

- name: Install user SSH key
  copy:
    src: "{{ ssh.user_key }}"
    dest: /home/{{ user }}/.ssh/id_rsa
    mode: 600
    owner:  "{{ user }}"
    group: "{{ user }}"
  when: ssh.user_key is defined