- tags: yay
  block:

    - name: Ensure `base-devel` is installed
      # Should be already installed, but just in case someone does not read the README.md file
      become: true
      community.general.pacman:
        state: latest
        name: base-devel

    - name: Check if yay already installed
      ansible.builtin.command: "which yay"
      register: which_yay
      ignore_errors: true

    - name: Install yay
      # https://github.com/Jguer/yay?tab=readme-ov-file#installation
      # Once installed this will never run again, update yay with yay itself
      when: which_yay.rc != 0
      block: 

      - name: Clone the `yay` repository
        ansible.builtin.git:
          repo: https://aur.archlinux.org/yay.git
          dest: "{{ home }}/git/yay"

      - name: Build
        # `-s` installs dependencies automatilly
        # `-i` install the package after successfully building it
        # `--noconfirm` answers `yes` to all prompts without asking questions
        ansible.builtin.shell: "cd {{ home }}/git/yay && makepkg -si --noconfirm"

