- name: Tap brew cask
  command: brew tap homebrew/cask-fonts

- name: Install base fonts
  homebrew:
    name: "{{ item.name | default(item) }}"
    state: latest
  loop: "{{ macos_fonts }}"
  when: ansible_distribution == "MacOSX"