- tags: fonts
  block:
    - name: Install fonts to Archlinux
      when: ansible_distribution == "Archlinux"
      include_tasks: archlinux.yml

    - name: Install fonts to Ubuntu
      when: ansible_distribution == "Ubuntu"
      include_tasks: ubuntu.yml

    - name: Install fonts to macOS
      when: ansible_distribution == "MacOSX"
      include_tasks: macos.yml

    # - name: Install AUR fonts
    #   aur:
    #     name: "{{ aur_fonts }}"
    #     user: "{{ user.name }}"
    #   tags:
    #     - aur
