---
collections:
  - name: ansible.windows
  - name: community.windows
  - name: community.general
  - name: chocolatey.chocolatey
  - name: geerlingguy.mac
  - name: kewlfft.aur

roles:
  - name: elliotweiser.osx-command-line-tools