- name: Install common tools (ArchLinux)
  become: true
  pacman:
    state: latest
    name: "{{ item.name | default(item) }}"
  loop: "{{ common_all }}"
  

- name: Install common Linux tools (ArchLinux)
  become: true
  pacman:
    state: latest
    name: "{{ item.name | default(item) }}"
  loop: "{{ common_linux }}"
