- name: Install common packages (macOS)
  homebrew:
    name: "{{ item.name | default(item) }}"
    state: latest
  loop: "{{ common_all }}"
  
- name: Install common *nix packages (macOS)
  homebrew:
    name: "{{ item.name | default(item) }}"
    state: latest
  loop: "{{ common_nix }}"