- tags: common
  block:

  - name: Install Archlinux Common Tools
    include_tasks: archlinux.yml
    when: ansible_distribution == "Archlinux"

  - name: Install Ubuntu Common Tools
    include_tasks: ubuntu.yml
    when: ansible_distribution == "Ubuntu"

  - name: Install macOS Common Tools
    include_tasks: macos.yml
    when: ansible_distribution == "MacOSX"