# ------------------------------------------------------------------------------

# Preferences:
#   These are the default values for all hosts. To apply different preferences between hosts use host preferences files (`host_vars` directory).

timezone: "America/Los_Angeles"
#   (password authentication is disabled by default for the root user. You can opt to disable password authentication for all other users as well)
ssh_disable_password_authentication: false

# command line only since this will be installed on servers as well
common_all:
    - bat                 # Cat clone with syntax highlighting and git integration (`cat` alternative)
    - fzf                 # Command-line fuzzy finder
    - zoxide              # A smarter cd command for your terminal (`cd` alternative)
    - vim                 # Easily usable by anyone
    - duf                 # Disk Usage/Free Utility (`df` alternative)
    - speedtest-cli       # Command line interface for testing internet bandwidth using speedtest.net
    - wget                # Network utility to retrieve files from the Web (used by Neovim to download files on the internet when pressing `gf`)
    - curl                # Network utility to retrieve files from the Web
    - nmap                # Utility for network discovery and security auditing (great to check open ports)
    - rsync               # A fast and versatile file copying tool for remote and local files (`cp` alternative)
    - trash-cli           # Command line trashcan (recycle bin) interface (`rm` alternative)
    - tldr                # Command line client for tldr, a collection of simplified and community-driven man pages
    - btop                # A graphical process/system monitor (`htop` alternative)
    - ncdu                # Disk usage analyzer like WinDirStat (`du` alternative)
    - dosfstools          # DOS filesystem utilities TODO:Remove?
    # - exfat-utils        # Utilities for exFAT file system TODO:Remove?
    - mtools              # A collection of utilities to access MS-DOS disks TODO: Remove?
    - p7zip               # Command-line file archiver with high compression ratio
    - unzip               # For extracting and viewing files in .zip archives
    - zip                 # Compressor/archiver for creating and modifying zipfiles
    - stow
    - zsh
    - tmux
    - neovim

common_linux:
    #- hwinfo              # Hardware detection tool from openSUSE
    - unrar               # The RAR uncompression program
    #- ethtool             # Utility for controlling network drivers and hardware
    #- traceroute          # Tracks the route taken by packets over an IP network

arch_pkgs:
    - vi                  # Called by ansible-vault and maybe others
    - eza                 # Modern replacement for ls, community fork of exa (`ls` alternative)
    - fd                  # Simple, fast and user-friendly alternative to find (`find` alternative)
    - pipewire-alsa       # Low-latency audio/video router and processor - ALSA configuration
    #- pipewire-jack       # Low-latency audio/video router and processor - JACK replacement
    - pipewire-pulse      # Low-latency audio/video router and processor - PulseAudio replacement
    - pavucontrol         # PulseAudio Volume Control
    - audacious           # Audio player
    - bandwhich           # Terminal bandwidth utilization tool
    - github-cli          # GitHub CLI
    - pyenv               # Easy python environment switcher
    - mpv           # A free, open source, and cross-platform media player
    - mpv-mpris     # MPRIS plugin for mpv (media keys)
    - libreoffice-fresh   # LibreOffice branch which contains new features and program enhancements
    - foliate             # A simple and modern GTK eBook reader
    - discord
    - chromium
    - calibre
    - obsidian
    - steam
    - firefox
    - evince              # Document viewer (PDF, PostScript, XPS, djvu, dvi, tiff, cbr, cbz, cb7, cbt)
    - fontconfig          # library for configuring and customizing font access
    - fastfetch           # A CLI system fetch information tool similar to neofetch
    - lazygit
    - eza

arch_aur_pkgs:
    - ferdium-bin
    - fnm                 # Fast node manager, needs to be pulled off AUR
    - github-desktop-bin
    - nomachine
    - protonup-qt
    - spotify
    - stretchly
    - typora          # unar and lsar: Objective-C tools for uncompressing archive files 
    - visual-studio-code-bin
    - wezterm-git
    - zoom

# expected to be server only
ubuntu_pkgs:
    - eza                 # Modern replacement for ls (`ls` alternative)
    - gh                  # GitHub CLI
#    - lazydocker          # Visual docker GUI for terminal TODO: move this out of here: https://lindevs.com/install-lazydocker-on-ubuntu/

macos_casks:
    - alt-tab
    - calibre
    - discord
    - eloston-chromium
    - ferdium
    - fig
    - github
    - karabiner-elements
    - libreoffice         # LibreOffice (fresh) branch which contains new features and program enhancements
    - mos
    - mpv
    - nomachine
    - notunes
    - obsidian
    - plex
    - raycast
    - rectangle
    - spotify
    - stretchly
    - the-unarchiver
    - typora          # unar and lsar: Objective-C tools for uncompressing archive files 
    - vanilla
    - visual-studio-code
    - vlc
    - wezterm
    - zoom
    - cask-fonts

install_homebrew_if_missing: true

# Calculated variables (no need to touch):
#   (lookup env will get the given environment variable from the controller machine. This is why we must execute this script via `ansible-pull` and while logged in as the user for which we want to generate the config files. For more info see: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/env_lookup.html#ansible-collections-ansible-builtin-env-lookup)
home: "{{ lookup('env', 'HOME') }}"
user: "{{ lookup('env', 'USER') }}"
#   (required for processor firmware updates)
is_intel: "{{ 'GenuineIntel' in ansible_processor }}"
