- name: mkdir -p /etc/apt/keyrings
  become: true
  ansible.builtin.shell: sudo mkdir -p /etc/apt/keyrings

- name: Get GPG key
  ansible.builtin.shell: wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o --batch --yes /etc/apt/keyrings/gierens.gpg

- name: Echo key
  become: true
  ansible.builtin.shell: echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list

- name: Chmod List
  become: true
  ansible.builtin.shell: sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list

- name: Make sure all packages are up to date in Ubuntu
  become: true
  ansible.builtin.apt:
    update_cache: true