- name: Install Ubuntu-specific packages
  become: true
  apt:
    state: latest
    name: "{{ ubuntu_pkgs }}"

- name: Install zoxide
  become: true
  ansible.builtin.shell: curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
