- tags: pre_install
  block:


    - name: pre-tasks - Make sure all packages are up to date
      become: true
      community.general.pacman:
        update_cache: true
        upgrade: true
      when: ansible_distribution != "Archlinux"