- tags: fonts
  block:

    - include_tasks: archlinux.yml
    - include_tasks: ubuntu.yml

    # - name: Install AUR fonts
    #   aur:
    #     name: "{{ aur_fonts }}"
    #     user: "{{ user.name }}"
    #   tags:
    #     - aur
