- tags: fonts
  block:

    - name: Install base fonts
      become: true
      community.general.pacman:
        name: "{{ base_fonts }}"
        state: present

    # - name: Install AUR fonts
    #   aur:
    #     name: "{{ aur_fonts }}"
    #     user: "{{ user.name }}"
    #   tags:
    #     - aur
